name: Test Build CI

on:
  push:
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn

    - name: Test build
      run: |
        node preset_build.js

    - name: Upload files built
      uses: actions/upload-artifact@v2
      with:
        name: files-built
        path: |
          builds
  deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: Update Deployment Status
       run: |
         curl \
         -X POST \
         -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/${{github.repository}}/deployments \
         -d '{"ref":"${{ github.sha }}", "required_contexts": []}'